version: '3.2'
services:
  service-netris:
    container_name: service-netris
    image: "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}"
    restart: always
    expose:
    - 8080
    environment:
    - "POSTGRES_HOST=${POSTGRES_HOST}"
    - "POSTGRES_PORT=${POSTGRES_PORT}"
    - "POSTGRES_DB=${POSTGRES_DB}"
    - "POSTGRES_USER=${POSTGRES_USER}"
    - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    - "BPM_HOST=${BPM_HOST}"
    # - "DB_JDBC_ADDRESS_WITH_DB=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    extra_hosts:
    - "corp.local:192.168.60.15"
    - "adc2.corp.local:192.168.250.34"
    - "db-germes.corp.local:192.168.60.42"
    - "directum.corp.local:192.168.60.7"
    networks:
    - private    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M
networks:
  private:
    external:
      name: compose_private
